# Generated by Django 4.2.28 on 2026-02-16 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CrimeRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month_year', models.CharField(db_index=True, max_length=20)),
                ('area_type', models.CharField(blank=True, default='', max_length=50)),
                ('borough_snt', models.CharField(blank=True, default='', max_length=100)),
                ('area_name', models.CharField(db_index=True, max_length=150)),
                ('area_code', models.CharField(blank=True, default='', max_length=20)),
                ('offence_group', models.CharField(db_index=True, max_length=150)),
                ('offence_subgroup', models.CharField(blank=True, default='', max_length=200)),
                ('measure', models.CharField(blank=True, default='', max_length=50)),
                ('financial_year', models.CharField(blank=True, default='', max_length=20)),
                ('fy_index', models.IntegerField(blank=True, null=True)),
                ('count', models.IntegerField(default=0)),
                ('refresh_date', models.CharField(blank=True, default='', max_length=30)),
            ],
            options={
                'indexes': [models.Index(fields=['month_year', 'area_name'], name='crime_crime_month_y_bc3641_idx'), models.Index(fields=['month_year', 'offence_group'], name='crime_crime_month_y_8d56c8_idx'), models.Index(fields=['area_name', 'offence_group'], name='crime_crime_area_na_fec598_idx')],
            },
        ),
    ]
