# Generated by Django 4.2.28 on 2026-02-17 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crime', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='crimerecord',
            name='area_code',
        ),
        migrations.RemoveField(
            model_name='crimerecord',
            name='borough_snt',
        ),
        migrations.RemoveField(
            model_name='crimerecord',
            name='financial_year',
        ),
        migrations.RemoveField(
            model_name='crimerecord',
            name='fy_index',
        ),
        migrations.RemoveField(
            model_name='crimerecord',
            name='measure',
        ),
        migrations.RemoveField(
            model_name='crimerecord',
            name='refresh_date',
        ),
    ]
